# Conclusion

Results presented here, indicates that: 1) biometric parameters explain better the salinity response than the germination parameters. Thus, genotypes 114, 171 and 183 would be considered interesting candidates for salt stress tolerance, whereas genotypes 133 and 218 show sensitivity to NaCl addition. 2) the viability of germination and oil content in seeds of *J. curcas* can be maintained provided if there is control of moisture in the interstices of the seed during storage. 3) considering only salt stress experiments we can somehow describes that genotypes, 114, 171 and 183 could be considered as potential candidates for future breeding programs.

# Acknowledgments

The authors thank the National Council for Scientific and Technological Development (CNPq Process nº 404357/2013-0) for the financial support. The first author thanks the Coordination of Improvement of Higher Education Personnel (CAPES) for the scholarship. Special thanks to Dr. Agnaldo Rodrigues de Melo Chaves, Tropical Semiarid Agricultural Research Center, Embrapa Semiárido, Petrolina, PE, Brazil and Embrapa Agroenergy, Brasília, DF, Brazil for giving the seeds used in this study. The authors would also like to extend special thanks to Mrs. Ana Maria Meucci Dal Cin for her teaching and dedication to better formation, which benefited Marcelo Francisco Pompelli, at about 30 years ago.