# Discussion

The seeds of *J. curcas* are classified as orthodox [@hay2013advances], resistant to desiccation, can often present water contents up to 18% [@pompelli2010environmental] when freshly harvested. Moncaleano-Escandon [@moncaleano2013germination], showed that the seeds of *J. curcas* can drastically reduce their germinability during storage at temperatures of 4°C or 25°C, accompanied by the reduction of some compounds such as starch and total soluble proteins. This author also showed that at 4°C it was more interesting for the storage of seeds of this species. In this work, we observed that the reduction of the relative humidity in the interstice of the seeds reduced the water content of the seeds and consequently the water potential . Coupled to these facts, the respiration rate were strongly reduced, but not zero, which allowed the viability of the embryo at the expense of the solubilization of reserves, that supported the germinability of the seeds during the storage without significant reduction. However, we shows a strong and positive correlation (r = 0.92, p ≤ 0.05) between total soluble proteins and amino acid syntheses. A possible explanation for this, could be that structural proteins were mobilized to generate carbon skeleton to respiration or amino acids as a compatible solutes that allows maintain the respiration even with reduction of seed moisture. Similarly to that described previously, we showed a significant correlation between decrease of sucrose and elevation to glucose (r = -0.87, p ≤ 0.05) and fructose (r = -0.56, p ≤ 0.05). The total soluble carbohydrates content must have been reduced by the metabolism of sucrose, which acted as the carbon source for the embryo. Circumstantial evidence of this idea is based on the elevation of glucose and fructose contents while there has been a reduction in the levels of starch and sucrose. Thus, the respiration rate, even low, foresees the live embryo, which allowed the germination, even 12 months after storage, a fact that diverges of Moncaleano-Escandon et al. (2013) [@moncaleano2013germination] which describes that the germination of *J. curcas* seeds drop near to zero after 12 months of storage, but six months after start of experiments the seeds stored in low temperature drop 27%, while in this experiment the germination remained stable during all storage time. It should be noted that Moncaleano-Escandon et al. (2013) [@moncaleano2013germination], stored its seeds without any type of desiccant and, in this study, seeds were stored at 4ºC as recommended by Moncaleano-Escandon et al. (2013) [@moncaleano2013germination], but in boxes with very low RH, promoted by the use of desiccant. Another high evidence of respiration was responsible for the mobilization of reserves can be corroborated by the strong negative correlation between oil, starch and sucrose contents with its degradation products (i.e., total soluble proteins, total soluble amino acids and glucose). In addition, it was reported that seeds  containing between 6% and 8% of moisture had a rapid reduction in seed oil content in the first 3 months of storage, together with an increase in the concentration of free fatty acids [@akowuah2012influence; @worang2008quality] Thus, it is verified that the moisture control in the interstice of the seeds should be taken into account to preserve both the viability and the oil content of the seeds of *J. curcas*.


The negative effects of saline stress were reflected in the delay in the mean germination time, from 3 days in the 0 mM NaCl and up to 13 days in 150 mM NaCl in the irrigation water, which is confirmed by the significant reduction in germination rate. Same patter was previously reported in *J. curcas* by Alencar et al. (2015) [@alencar2015ultrastructural] which describes a strong and negative correlation between germination rate and mean germination time. Regardless of the storage time, germination was initiated between the third and fifth day, with complete finishing after 23 days of sowing, which occurred mainly with 12 months of storage. Both salinity and storage delayed germination; But among them, storage seems to be the factor that slows down germinability with greater magnitude.  It was observed that the germination synchrony was reduced with the increase of the salts concentration, and the salinity stress promoted slow and more disorganized germination, a fact corroborated by the high values of germination uncertainty. That *J. curcas* has an asynchrony in germination, mainly in salt stress, is already very well studied [@alencar2015ultrastructural; @islam2009effect; @moncaleano2013germination; @pompelli2010environmental; @silva2012relationship]. Therefore, if we analyze the previously published data with those presented of this study we can postulate that synchrony and the uncertainty of the germination can not be considered a good parameters for judgment, at least in *J. curcas*. A possible explanation for this could arise from the fact that *J. curcas* is not yet a domesticated species [@achten2010towards], which makes it present high levels of uncertainty in germination [@ranal2006and]; A factor highly related to the survival of the species in its original habitat [@maes2009climatic] and very unstable from the physiological point of view. Seeds of *J. curcas* can not tolerate up to 150 mM NaCl in the irrigation water for seed germination, and it has very difficulties for seedlings development in concentrations above 75 mM of NaCl. The delay of the germination accompanied with the decrease of the development of the leaves and the reduction of the root growth promotes delay of the autotrophic phase of the plants, in extreme cases, leads to the death of the seedling in the first days after germination. A possible explanation for this is presented by Alencar et al. (2015) [@alencar2015ultrastructural] since there was a great increase of the Na+ and Cl- contents in the embryonic axes and in the endosperm of the seeds of *J. curcas*. Another possibility is loss of mobilization  of cotyledon reserves on germination [@liu2010seed] affecting seedling establishment [@marques2013increased]. 

It  is common for plants to increase their stem biomass to the detriment of other organs when subjected to salinity [@dantas2007germination; @munns1986whole; @praxedes2010salt]. Munns [@munns1986whole] describes this as an indirect effect of decreasing water uptake by roots and lower leaf expansion, while Praxedes [@praxedes2010salt] describes this effect as lower relative growth rate of the plant as a whole. On the other hand, Bayuelo-Jiménez [@bayuelo2002salinity] and Debez [@debez2004salinity] describe that all biometric components are reduced in plants submitted to salinity, whether this species is salinity sensitive [@bayuelo2002salinity] or a halophyte [@debez2004salinity]. In addition, Hasewaga [@hasegawa2000plant] attributed this reduction and/or inhibition of plant growth, when subjected to salinity, to a number of factors such as changes in the water status of the plant caused by the osmotic effect of the salts, increase in the concentration of toxic ions, producing physiological and biochemical variations and alteration in the absorption of essential nutrients. Principal component analysis showed that the biometric parameters explain better the salinity response than the germination parameters. Genotypes 114, 171 and 183 are possible candidates for salt stress tolerance, whereas genotypes 133 and 218 show sensitivity to NaCl addition in the irrigation water. 

In conclusion the viability of germination and oil content in seeds of *Jatropha curcas* can be maintained provided there is control of moisture in the interstices of the seed during storage. Salinity strongly affects the germination and initial development of *Jatropha curcas*, and from the evaluated genotypes, 114, 171 and 183 present as potential candidates for future breeding programs. 
