# Introduction

_Jatropha curcas_ (purgint nut) is a species belonging to the family Euphorbiaceae with multiple uses, abundantly distributed in many tropical and subtropical regions in the Americas, Africa and Asia [@heller1996physic; @takeda1982development]. Over the last 20 years they have gained a lot of attention as a potential crop for bioenergy production, since their seed oil can easily be converted to good quality biodiesel. In addition, the species does not present as edible and therefore does not compete with the other oilseeds [@Pompelli2011]. It has a high growth rate, easy propagation, short period until the first fruit harvest, low seed cost  [@heller1996physic], high oil content (40-58%) [@pandey2012jatropha; @pompelli2010environmental], and good adaptation to different agroclimatic conditions [@Divakara2010; @fini2013water; @gao2008effects].

Germination is the process that determines when and where the seeds will initiate their growth [@gunster1994seed], allowing the embryo to germinate and develop as a photosynthetically active organism. It begins with the imbibition of the quiescent seed and ends as the elongation of the embryonic axis, which can be visualized by the emergence of soil surface. At the moment, the reserves contained in the seeds begin to be mobilized by yielding energy to the developing embryo [@bewley2013mobilization; @sanchez2012early]. In this sense, salinity can affect germination, limiting the absorption of water in the seeds (osmotic effect) [@almansouri2001effect; @hegarty1977seed] increases the toxicity by ions or the combination of both [@apse1999salt]. In addition, NaCl may affect the mobilization of reserves [@bouaziz1990consumption], structural organization and protein synthesis in embryos [@alencar2015ultrastructural]. In saline environments, plant adaptation during germination are decisive stages for species establishment, and such factors may negatively influence this process [@ungar1995seed].

If we take into account that _J. curcas_ is a potential species for the large-scale generation of biodiesel, it is easy to think that it will be necessary to plant hundreds or thousands of hectares of trees to produce a satisfactory amount for commercial exploitation [@contran2013state; @yang2010selection]. In this sense, it is also salutary to remember that in times of harvest market prices usually fall a lot [@sumner1989harvest] and that is where the storage of seeds comes in. However, seed storage is the most factor that negatively affects seed viability, which includes the time elapsed between harvesting and utilization [@marcos1984testes; @marcos1998new]. Marcos-Filho [@marcos1998new] describes that seed storage is a major problem for agriculture [@tekrony2006seeds], since it is responsible for large losses worldwide, especially in the tropics, where high temperatures and high relative humidity prevail during seed maturation and storage [@bilia1994comportamento]. _J. curcas_ does not escape this pattern, since it presents high metabolism, causing its seeds to rapidly lose their viability with storage [@moncaleano2013germination]. Although deterioration is irreversible and unavoidable, the speed of the process can be controlled by appropriate harvesting, drying and storage techniques [@sumner1989harvest]. In this sense, the use of drier atmosphere environments could protect seeds [@hay2012evaluation; @hay2013advances; @rao2006storability].

Another factor that negatively influences agriculture is salinity, mainly in irrigated crops [@kumar2008effects], with NaCl being the predominant salt. Approximately 20% of the world's cultivated land is affected by salts [@sun2009nacl]. This problem is more relevant in arid and semiarid regions, where the lack of rainfall and the high evaporative demand caused by high temperatures and low relative humidity contribute to soil salinity intensification. In addition, salinity affects plant growth and development [@munns2008mechanisms], negatively influencing different stages of its development [@almansouri2001effect; @khajeh2003interaction; @khan2003light]. However, throughout their evolution, plants have developed mechanisms for regulation and tolerance to salts.

Some studies have described the ecophysiological aspects of the tolerance of *J. curcas* to NaCl [@diaz2012tolerance; @elhag2014effect; @pompelli2010photosynthesis; @rajaona2012effect]; However, these studies focused on only one genotype. Although interest in the growth response of *J. curcas* is increasing, there is no known research that has examined the effect of NaCl on different genotypes during germination and early development of seedlings. In this work five distinct genotypes of *J. curcas* exposed to different NaCl treatments were studied to determine tolerance and to understand the morphological and physiological responses of this species under conditions of salinity in their germination and initial development.

Thus, the main hypotheses of this work were (i) to verify if the use of a desiccant agent could help to maintain the viability and germinability of the seeds of *J. curcas* when stored for long periods of time, and (ii) to study the mechanims of the tolerance of *J. curcas* to salinity between the genotypes cultivated in Brazil.

