# Results

## Germination of aged seeds.

The germination of the *J. curcas* seeds submitted to storage ranged from 9% to 15%, with values that are statistically similar to each other (Figure \@ref(fig:germination)A). Although germination was not affected by storage, the mean germination time was significantly increased with storage time (Figure \@ref(fig:germination)B). The germination was completely asynchronous for all storage times, with a mean of 0.16 being recorded before storage and close to zero at other times (Figure \@ref(fig:germination)C). As it was observed, the germination in the time was significantly affected by the storage time. However, the germination uncertainty was not affected by the storage (Figure \@ref(fig:germination)D). It is verified that the seeds before storage and stored for 3 months began their germination on the 3^rd^ and the 4^th^ day after sowing respectively, while in other times the germination of the first seed was only computed from the 6^th^ day. The time for stabilization of the germination was increased as the storage time was increased, being completed at 15 days without storage and at 23 days at 12 months of storage.

## Biochemical responses of seeds submitted to aging.

It was verified that the oil content in the seeds remained practically stable until the sixth month of storage at the rate of 35%, with significant reductions from 12th month of storage, when the oil content was approximately 29% (Figure \@ref(fig:bioquimico)A). We verified a strong and negative correlation between oil content in the seeds and storage time (r = -0.91, p ≤ 0.05). On the other hand, the starch was rapidly metabolized with approximate reduction of 33% with time 12 months of storage (Figure \@ref(fig:bioquimico)B). Total soluble protein and total soluble amino acid content was increased by 160% and approximately 67% during storage (Figure \@ref(fig:bioquimico)C-D). A strong and positive correlation (r = 0.92, p ≤ 0.05) is shown between total soluble proteins and amino acid syntheses. There was a gradual reduction in the total soluble carbohydrate content at the 3^rd^ month of storage compared to the control, without showing differences until the 12^th^ month of storage (Figure \@ref(fig:bioquimico2)A). Sucrose levels had a reduction of approximately 49% between 3 and 12 months of storage (Figure \@ref(fig:bioquimico)B), while glucose levels remained stable until the 3^rd^ month of storage when compared to non-stored seeds. From the 6^th^ month, the glucose was rapidly elevated, reaching 71% in the 12^th^ month in relation to the non-stored seeds  (Figure \@ref(fig:bioquimico2)C). On the other hand, fructose levels did not show a trend during the months evaluated  (Figure \@ref(fig:bioquimico2)D). We showed that while sucrose levels decreased (r = -0.57, p ≤ 0.05) throughout the storage period, glucose (r = 0.67, p ≤ 0.05) had an opposite behavior, with increase with storage.

## Physiological responses of seeds submitted to aging.

With the storage time in desiccant agent, it was verified that the water content in the seeds was greatly reduced (Figure \@ref(fig:fisio)). Non-stored seeds had 8% of water content, while seeds stored by 12 months had 5.5% (Figure \@ref(fig:fisio)A). Concomitantly the water content, the seeds water potential had a strong reduction with the storage time, presenting a strong correlation (r = 0.83, p ≤ 0.05) between these two characteristics. We verified that the water potential of non-stored seeds were -35 MPa, but water potential were reduced to -124 MPa at 12 months of storage (Figure \@ref(fig:fisio)B). With the reduction of the relative water content and the water potential there was a strong reduction in the respiratory rate of the seeds (r = 0.88, p ≤ 0.05), ranging 115 mmol CO~2~ h^-1^ g^-1^ MF, in non-stored seeds to 10 mmol CO~2~ h^-1^ g^-1^ MF after 12 months of storage (Figure \@ref(fig:fisio)), a reduction of 91% over the seeds storage (Figure \@ref(fig:fisio)C).

## Seed germination treated with NaCl.

These experiments were conducted in greenhouse condition. The temperature was 30.6 ± 1.1°C and relative humidity of 70.4 ± 5.8%. The environmental data were collected every fifteen minutes during all days, 24 hours per day. In this experiment, we verified that the germination was almost zero at 150 mM NaCl for all genotypes. In 0 mM NaCl, seeds of genotype 183 and 114 had 71% and 86% of germination, respectively, with gradual decrease with the increase in NaCl concentration, from 4% to 100 mM and 0% to 150 mM. In another way, genotypes 218 and 133 did not differ by up to 100 mM NaCl, although germination was reduced to approximately 5% at the concentration of 150 mM. Seeds of the genotype 171 showed 65% germination in the control, reducing to 32% and 9% in 50 mM and 150 mM NaCl respectively (Figure \@ref(fig:jcger)A). The mean germination time for 0 mM NaCl was 5 to 7 days for all genotypes, while for the 150 mM NaCl concentration the interval was longer, ranging from 7.2 days to 12.3 days. No significant differences were observed in mean germination time from 50 mM to 75 mM, with a general average of 7.5 days for all genotypes (Figure \@ref(fig:jcger)B). There was no difference in the germination synchrony for the genotypes up to 75 mM NaCl. However, the synchronization at 100 mM was null at genotype 183, 114 and 218, as well as for genotype 133 in the concentration at 150 mM NaCl. It was observed that the synchrony were always lower than 0.25 for all concentrations and genotypes (Figure \@ref(fig:jcger)C), denoting a asynchronous profile. The maximum value for the uncertainty in germination in this experiment was 4.64 bits. Genotypes 183 and 114 showed a tendency to reduce uncertainty with the increase in NaCl concentration. The germination uncertainty was stable up to 75 mM NaCl, but with a significant increase in the concentration of 100 mM, where the uncertainty was 0.5 and 0.3 for the genotype 183 and 114, respectively. Genotypes 218, 171 and 133 showed a trend in increasing uncertainty from 0 mM to 100 mM without showing significant differences. At 150 mM, the uncertainty was 0.3, 0.7 and 0.5 for genotypes 218, 171 and 133 respectively (Figure \@ref(fig:jcger)D). The  germination in time showed differences for each of the genotypes. The germination in the treatments without salt began between the 3^rd^ and 4^th^ day after sowing; for the treatments with NaCl addition the maximum values of germination were observed between the 9^th^ and 12^th^ day (Figure \@ref(fig:gerit)A-E). Regardless of the genotypes, first germination was observed on the 3^rd^ day in 0 mM NaCl, while in the 50 mM and 75 mM NaCl, the germination was generally initiated on the 4^th^ day, but arranged 5^th^ day and 7^th^ day in 100 mM and 150 mM NaCl, respectively. However, regardless of treatments and salinity levels, germination became stable since 13^th^ day (Figure \@ref(fig:gerit)).

## Biometric and biomass components.

Although the germination was evaluated up to the concentration of 150 mM NaCl, the biomass production was only computed up to 100 mM NaCl because above this concentration the plants did not have enough vigor to resist salinity and eventually languished. The biomass parameters were strongly affected by the increase in salinity. There was a reduction trend for plant height (HGT) with  salt increasing. The HGT reached approximately 13 cm in the control, but was strongly reduced until values smaller than 3 cm to 100 Mm of NaCl, fact clearly recorded in genotype 183 (Figure \@ref(fig:index)A). The root dry weight ratio (RWR) showed a distinct behavior for each genotype, with genotypes 171, 133 and 218, increasing biomass of the roots up to 75 mM. On the other hand, the genotype 183 showed increment up to 50 mM and from there had its values reduced. Genotype 114 was apparently unaffected by the increase in NaCl concentration (Figure \@ref(fig:index)B). The stem diameter (STD) presented reduction with the increase of the concentration of NaCl, even without statistical differences for concentration from 50 to 100 Mm for genotypes 218, 171 and 133. At concentrations of 100 mM the genotype 183 had the lowest values for STD (Figure \@ref(fig:index)C). A distinct profile is verified in the stem dry weight ratio (SWR), which was increased with elevation of salinity, even though no significant effect was observed up to the 50 mM concentration. For the 75 mM concentration, genotype 183 was better performance than the other while the genotypes 183, 171 and 133 for 100 mM concentration (Figure \@ref(fig:index)D). The leaf area (LFA) was possible to be evaluated until the concentration of 75 mM NaCl, since these was the most affected parameter by the increase of NaCl in the irrigation solution. The genotypes 218 presented the highest values for the control concentration, while for 50 mM the genotypes 133, 114 and 183 showed the highest performance. For the leaf dry weight ratio  (LWR), it is possible to observe a trend in the reduction of biomass according salinity increase, being genotype 218 presenting a ratio of 0.42, followed by genotype 183 with a ratio of 0.39 for 0 mM treatment. Genotype 171 did not show significant difference in leaf weight ratio up to 50 mM, while genotype 114 increased his biomass accumulation to 50 mM. All genotypes showed drastic reduction of LWR since 75 mM NaCl (Figure \@ref(fig:index)F). 


## Multivariate analysis of the salinity experiment.

The germination parameters were negatively affected by the increase in the salt concentration; There was a negative correlation between germination percentage (r = -0.55, p ≤ 0.05) and germination synchrony (r = -0.69, p ≤ 0.001). On the other hand, the mean germination time was positively significant when correlated with the increase of salts (r = 0.66, p ≤ 0.001). However, there was no significant correlation between germination uncertainty and salt increase (r = -0.23, p = 0.321). The salt concentration affected all biomass parameters, e.g., r = -0.86 (to leaf dry weight), r = -0.89 (to leaf area), and r = -0.89 (to plant height) and r = -0.91 (to stem diameter). Likewise, all growth ratios were negatively influenced by salt adicion, e.g., r = -0.90 (to leaf weight ratio), r = -0.94 (to leaf area ratio). Unlike stem dry weight ratio were positively influenced (r = 0.74) by salt adition. The principal components analysis (PCA) shows that approximately 74.4% of the variation can be explained by the parameters studied in this work. In the first component the variables LDW, LFA, HGT and TDW were the ones that presented the greatest contribution in the variance and are negatively correlated with the increase of NaCl, while the variables with positive correlation were the MGT and SWR. The genotypes 114, 171 and 183 were the bested between all tested and genotypes 133 and 218 seemingly were salt susceptible (Figure \@ref(fig:pca)). 
